/*
 * This source file was generated by the Gradle 'init' task
 */
package sudoku;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appCanBeCreated() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app instance should be created");
    }
}
