/*
 * This source file was generated by the Gradle 'init' task
 */
package sudoku;

import sudoku.ui.GameController;

public class App {
    public static void main(String[] args) {
        new GameController().run();
    }
}
